import image from '../images/mobile.jpg';

const ProductsInfo = [
  {
    title: 'Samsung',
    description: 'A20, blue',
    price: 150,
    condition: 'used',
    category: 'electronics',
    date: '03/25/2021',
    image: image,
  },
  {
    title: 'Dining Room Chairs',
    description: 'brown, 4 chairs',
    price: 200,
    condition: 'like new',
    category: 'furniture',
    date: '03/25/2016',
    image: image,
  },
  {
    title: 'LG Television',
    description: '37 inch',
    price: 300,
    condition: 'new',
    category: 'electronics',
    date: '03/25/2009',
    image: image,
  },
  {
    title: 'Gazelle Bicycle',
    description: 'for woman',
    price: 100,
    condition: 'used',
    category: 'bicycles',
    date: '03/25/2018',
    image: image,
  },
  {
    title: 'Beko',
    description: 'A20, blue',
    price: 150,
    condition: 'used',
    category: 'electronics',
    date: '03/25/2002',
    image: image,
  },
  {
    title: 'HP',
    description: 'A20, blue',
    price: 150,
    condition: 'used',
    category: 'electronics',
    date: '03/25/2010',
    image: image,
  },
  {
    title: 'AEG',
    description: 'A20, blue',
    price: 150,
    condition: 'used',
    category: 'electronics',
    date: '03/25/2012',
    image: image,
  },
  {
    title: 'Bosch',
    description: 'A20, blue',
    price: 150,
    condition: 'used',
    category: 'electronics',
    date: '03/25/2014',
    image: image,
  },
  {
    title: 'LG',
    description: 'A20, blue',
    price: 150,
    condition: 'used',
    category: 'electronics',
    date: '03/25/2009',
    image: image,
  },
  {
    title: 'Apple',
    description: 'A20, blue',
    price: 150,
    condition: 'used',
    category: 'electronics',
    date: '03/25/2008',
    image: image,
  },
  {
    title: 'Tblet',
    description: 'for woman',
    price: 100,
    condition: 'used',
    category: 'bicycles',
    date: '10/25/2014',
    image: image,
  },
  {
    title: 'Smart Phone',
    description: 'A20, blue',
    price: 150,
    condition: 'used',
    category: 'electronics',
    date: '12/10/2002',
    image: image,
  },
  {
    title: 'Dell',
    description: 'A20, blue',
    price: 150,
    condition: 'used',
    category: 'electronics',
    date: '10/03/2013',
    image: image,
  },
  {
    title: 'Computer',
    description: 'A20, blue',
    price: 150,
    condition: 'used',
    category: 'electronics',
    date: '05/22/2012',
    image: image,
  },
  {
    title: 'Intel',
    description: 'A20, blue',
    price: 150,
    condition: 'used',
    category: 'electronics',
    date: '06/20/2021',
    image: image,
  },
  {
    title: 'Ulker',
    description: 'A20, blue',
    price: 150,
    condition: 'used',
    category: 'electronics',
    date: '04/30/2017',
    image: image,
  },
  {
    title: 'Microsoft',
    description: 'A20, blue',
    price: 150,
    condition: 'used',
    category: 'electronics',
    date: '07/01/2020',
    image: image,
  },
];
export default ProductsInfo;
